from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).parent.resolve()
WEB_DIR = ROOT / 'web'
OUTPUT = ROOT / 'src' / 'web_assets.py'

ASSET_MAP = {
    'LOGIN_HTML': WEB_DIR / 'login.html',
    'INDEX_HTML': WEB_DIR / 'index.html',
    'PORTAL_CSS': WEB_DIR / 'portal.css',
    'PORTAL_JS': WEB_DIR / 'portal.js',
}

HEADER = (
    '# Generated by asset_pipeline.py\n'
    '# ruff: noqa: E501\n'
    '# Source files live under web/.\n\n'
)


def render_web_assets() -> str:
    lines = [HEADER]
    for name, path in ASSET_MAP.items():
        text = path.read_text(encoding='utf-8')
        lines.append(f'{name} = {json.dumps(text, ensure_ascii=False)}\n\n')
    lines.append('__all__ = ' + json.dumps(list(ASSET_MAP)) + '\n')
    return ''.join(lines)


def sync_web_assets(check: bool = False) -> bool:
    rendered = render_web_assets()
    current = OUTPUT.read_text(encoding='utf-8') if OUTPUT.exists() else None
    if current == rendered:
        return False
    if check:
        raise SystemExit('src/web_assets.py is out of date. Run asset sync first.')
    OUTPUT.write_text(rendered, encoding='utf-8')
    return True
