#!/usr/bin/env python3

import argparse
import ast
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).parent.resolve()
SRC_DIR = ROOT / 'src'
OUTPUT = ROOT / 'dist' / 'boot.py'
ENTRY_MODULE = 'main'
GENERATED_HEADER = '# Generated by build.py\n# ruff: noqa: E501\n\n'
OVERRIDE_ENV = {
    'AP_SSID': 'PICO_BIT_AP_SSID',
    'AP_PASSWORD': 'PICO_BIT_AP_PASSWORD',
    'ALLOW_UNSAFE': 'PICO_BIT_ALLOW_UNSAFE',
}

os.chdir(ROOT)
OUTPUT.parent.mkdir(exist_ok=True)


def _is_docstring(expr):
    return (
        isinstance(expr, ast.Expr)
        and isinstance(expr.value, ast.Constant)
        and isinstance(expr.value.value, str)
    )


def _is_print_call(expr):
    return (
        isinstance(expr, ast.Expr)
        and isinstance(expr.value, ast.Call)
        and isinstance(expr.value.func, ast.Name)
        and expr.value.func.id == 'print'
    )


def _module_name(path):
    relative = path.relative_to(SRC_DIR)
    parts = list(relative.parts)
    if parts[-1] == '__init__.py':
        parts = parts[:-1]
    else:
        parts[-1] = parts[-1][:-3]
    return '.'.join(parts)


def _discover_modules():
    modules = {}
    for path in sorted(SRC_DIR.rglob('*.py')):
        if '__pycache__' in path.parts:
            continue
        modules[_module_name(path)] = path
    return modules


def _is_local_module(module_name, local_modules):
    if not module_name:
        return False
    if module_name in local_modules:
        return True
    prefix = module_name + '.'
    return any(local_name.startswith(prefix) for local_name in local_modules)


def _package_parts(module_name, path):
    parts = module_name.split('.')
    if path.name == '__init__.py':
        return parts
    return parts[:-1]


def _resolve_import_from(module_name, path, imported_module, level):
    if level == 0:
        return imported_module or ''

    package_parts = _package_parts(module_name, path)
    trim = level - 1
    if trim > len(package_parts):
        return imported_module or ''

    base_parts = package_parts[: len(package_parts) - trim]
    if imported_module:
        base_parts.extend(imported_module.split('.'))
    return '.'.join(part for part in base_parts if part)


def _import_dependencies(base_module, names, local_modules):
    dependencies = set()

    if base_module and _is_local_module(base_module, local_modules):
        dependencies.add(base_module)

    if base_module:
        for alias in names:
            candidate = f'{base_module}.{alias.name}'
            if candidate in local_modules:
                dependencies.add(candidate)

    return dependencies


def _extract_local_dependencies(module_name, path, tree, local_modules):
    dependencies = set()

    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                if _is_local_module(alias.name, local_modules):
                    dependencies.add(alias.name)
        elif isinstance(node, ast.ImportFrom):
            base_module = _resolve_import_from(module_name, path, node.module, node.level)
            dependencies.update(_import_dependencies(base_module, node.names, local_modules))

    dependencies.discard(module_name)
    return dependencies


def _reachable_modules(entry_module, dependency_graph):
    reachable = set()

    def visit(module_name):
        if module_name in reachable or module_name not in dependency_graph:
            return
        reachable.add(module_name)
        for dependency in dependency_graph[module_name]:
            visit(dependency)

    visit(entry_module)
    return reachable


def _ordered_modules(entry_module, modules, dependency_graph):
    reachable = _reachable_modules(entry_module, dependency_graph)
    ordered = []
    visiting = set()
    visited = set()

    def visit(module_name):
        if module_name not in reachable or module_name in visited:
            return
        if module_name in visiting:
            raise RuntimeError(f'cyclic local import detected at {module_name}')

        visiting.add(module_name)
        for dependency in sorted(dependency_graph[module_name]):
            visit(dependency)
        visiting.remove(module_name)
        visited.add(module_name)
        ordered.append(module_name)

    visit(entry_module)

    for module_name in sorted(reachable):
        visit(module_name)

    return [module_name for module_name in ordered if module_name in modules]


class _Bundler(ast.NodeTransformer):
    def visit_Module(self, node):
        node.body = self._filter_body(node.body)
        return self.generic_visit(node)

    def visit_FunctionDef(self, node):
        node.body = self._filter_body(node.body, ensure_non_empty=True)
        return self.generic_visit(node)

    def visit_AsyncFunctionDef(self, node):
        node.body = self._filter_body(node.body, ensure_non_empty=True)
        return self.generic_visit(node)

    def visit_ClassDef(self, node):
        node.body = self._filter_body(node.body, ensure_non_empty=True)
        return self.generic_visit(node)

    def visit_If(self, node):
        node.body = self._filter_body(node.body, ensure_non_empty=True)
        node.orelse = self._filter_body(node.orelse)
        return self.generic_visit(node)

    def visit_For(self, node):
        node.body = self._filter_body(node.body, ensure_non_empty=True)
        node.orelse = self._filter_body(node.orelse)
        return self.generic_visit(node)

    def visit_While(self, node):
        node.body = self._filter_body(node.body, ensure_non_empty=True)
        node.orelse = self._filter_body(node.orelse)
        return self.generic_visit(node)

    def visit_With(self, node):
        node.body = self._filter_body(node.body, ensure_non_empty=True)
        return self.generic_visit(node)

    def visit_Try(self, node):
        node.body = self._filter_body(node.body, ensure_non_empty=True)
        node.orelse = self._filter_body(node.orelse)
        node.finalbody = self._filter_body(node.finalbody)
        for handler in node.handlers:
            handler.body = self._filter_body(handler.body, ensure_non_empty=True)
        return self.generic_visit(node)

    def visit_Import(self, node):
        return None

    def visit_ImportFrom(self, node):
        return None

    def _filter_body(self, body, ensure_non_empty=False):
        filtered = []
        for stmt in body:
            if _is_docstring(stmt) or _is_print_call(stmt):
                continue
            filtered.append(stmt)
        if ensure_non_empty and not filtered:
            filtered.append(ast.Pass())
        return filtered


class _OverrideInjector(ast.NodeTransformer):
    def __init__(self, overrides):
        self._overrides = overrides

    def visit_Assign(self, node):
        if len(node.targets) == 1 and isinstance(node.targets[0], ast.Name):
            name = node.targets[0].id
            if name in self._overrides:
                node.value = ast.Constant(value=self._overrides[name])
        return self.generic_visit(node)

    def visit_AnnAssign(self, node):
        if isinstance(node.target, ast.Name) and node.target.id in self._overrides:
            node.value = ast.Constant(value=self._overrides[node.target.id])
        return self.generic_visit(node)


def _extract_imports(module_name, path, tree, local_modules):
    imports = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            kept = [
                alias for alias in node.names if not _is_local_module(alias.name, local_modules)
            ]
            if kept:
                imports.append(ast.Import(names=kept))
        elif isinstance(node, ast.ImportFrom):
            base_module = _resolve_import_from(module_name, path, node.module, node.level)
            if node.level > 0 or _is_local_module(base_module, local_modules):
                continue
            imports.append(ast.ImportFrom(module=node.module, names=node.names, level=node.level))
    return imports


def _import_key(node):
    if isinstance(node, ast.Import):
        return (
            'import',
            tuple((alias.name, alias.asname) for alias in node.names),
        )
    return (
        'from',
        node.module,
        node.level,
        tuple((alias.name, alias.asname) for alias in node.names),
    )


def _dedupe_imports(imports):
    seen = set()
    result = []
    for node in imports:
        key = _import_key(node)
        if key in seen:
            continue
        seen.add(key)
        result.append(node)
    return result


def _sort_imports(imports):
    return sorted(
        imports,
        key=lambda node: (
            0 if isinstance(node, ast.Import) else 1,
            ast.unparse(node),
        ),
    )


def _parse_source(path):
    source = path.read_text(encoding='utf-8')
    return ast.parse(source, filename=str(path))


def _apply_overrides(module_name, tree, build_overrides):
    overrides = build_overrides.get(module_name)
    if not overrides:
        return tree
    overridden = _OverrideInjector(overrides).visit(tree)
    ast.fix_missing_locations(overridden)
    return overridden


def _parse_bool_flag(raw_value):
    value = raw_value.strip().lower()
    if value in {'1', 'true', 'yes', 'on'}:
        return True
    if value in {'0', 'false', 'no', 'off'}:
        return False
    if value == 'default':
        return None
    raise ValueError('allow unsafe must be one of: true, false, 1, 0, yes, no, on, off, default')


def _optional_env(name):
    value = os.environ.get(name)
    if value is None:
        return None
    return value.strip()


def _validate_config_value(name, value):
    if name == 'AP_SSID' and not 1 <= len(value) <= 32:
        raise ValueError('AP SSID must be between 1 and 32 characters')
    if name == 'AP_PASSWORD' and not 8 <= len(value) <= 63:
        raise ValueError('AP password must be between 8 and 63 characters')


def _build_overrides(args):
    raw_values = {
        'AP_SSID': (
            args.ap_ssid if args.ap_ssid is not None else _optional_env(OVERRIDE_ENV['AP_SSID'])
        ),
        'AP_PASSWORD': (
            args.ap_password
            if args.ap_password is not None
            else _optional_env(OVERRIDE_ENV['AP_PASSWORD'])
        ),
    }
    mode_value = (
        args.allow_unsafe
        if args.allow_unsafe is not None
        else _optional_env(OVERRIDE_ENV['ALLOW_UNSAFE'])
    )

    overrides = {}
    for name, value in raw_values.items():
        if value is None:
            continue
        _validate_config_value(name, value)
        overrides[name] = value

    if mode_value:
        overrides['ALLOW_UNSAFE'] = _parse_bool_flag(mode_value)

    overrides = {name: value for name, value in overrides.items() if value is not None}
    if not overrides:
        return {}
    return {'device_config': overrides}


def _clean_output_dir():
    for path in OUTPUT.parent.iterdir():
        if path == OUTPUT:
            continue
        if path.is_dir():
            shutil.rmtree(path)
            continue
        if path.is_file():
            path.unlink()


def _process_source(module_name, path, local_modules, build_overrides):
    tree = _apply_overrides(module_name, _parse_source(path), build_overrides)
    imports = _extract_imports(module_name, path, tree, local_modules)
    stripped = _Bundler().visit(tree)
    ast.fix_missing_locations(stripped)
    return imports, stripped.body


def _run_ruff(*args):
    subprocess.run(
        [sys.executable, '-m', 'ruff', *args, str(OUTPUT)],
        cwd=ROOT,
        check=True,
    )


def _post_process_output():
    print(f'Post-processing {OUTPUT.relative_to(ROOT)} with Ruff')
    _run_ruff('format')
    _run_ruff('check', '--fix', '--unsafe-fixes')
    _run_ruff('format')
    _run_ruff('check')


def build(build_overrides=None):
    if build_overrides is None:
        build_overrides = {}
    modules = _discover_modules()
    if ENTRY_MODULE not in modules:
        raise RuntimeError(f'entry module {ENTRY_MODULE!r} not found under {SRC_DIR}')

    local_modules = set(modules)
    dependency_graph = {}
    for module_name, path in modules.items():
        dependency_graph[module_name] = _extract_local_dependencies(
            module_name,
            path,
            _parse_source(path),
            local_modules,
        )

    ordered_modules = _ordered_modules(ENTRY_MODULE, modules, dependency_graph)

    imported_nodes = []
    bundled_body = []
    _clean_output_dir()
    for module_name in ordered_modules:
        path = modules[module_name]
        print(f'Bundling {path.relative_to(ROOT)}')
        imports, body = _process_source(module_name, path, local_modules, build_overrides)
        imported_nodes.extend(imports)
        bundled_body.extend(body)

    module = ast.Module(
        body=_sort_imports(_dedupe_imports(imported_nodes)) + bundled_body,
        type_ignores=[],
    )
    ast.fix_missing_locations(module)

    output = ast.unparse(module)
    output = GENERATED_HEADER + re.sub(r'\n{3,}', '\n\n', output).strip() + '\n'
    OUTPUT.write_text(output, encoding='utf-8')
    _post_process_output()
    final_size = OUTPUT.stat().st_size

    print(f'Done -> {OUTPUT.relative_to(ROOT)} ({final_size} bytes)')


def _build_parser():
    parser = argparse.ArgumentParser(description='Bundle the Pico runtime into dist/boot.py.')
    parser.add_argument(
        '--ap-ssid',
        help='Override the setup-mode access-point name for the generated bundle.',
    )
    parser.add_argument(
        '--ap-password',
        help='Override the setup-mode access-point password for the generated bundle.',
    )
    parser.add_argument(
        '--allow-unsafe',
        help='Override allow-unsafe in the generated bundle (true, false, or default).',
    )
    return parser


def main(argv=None):
    parser = _build_parser()
    args = parser.parse_args(argv)
    try:
        overrides = _build_overrides(args)
    except ValueError as exc:
        parser.error(str(exc))
    build(overrides)


if __name__ == '__main__':
    main()
