from __future__ import annotations

import ast
import subprocess
import sys
from pathlib import Path


def test_build_cleans_dist_to_expected_artifacts() -> None:
    root = Path(__file__).resolve().parents[1]
    dist = root / 'dist'
    stale = dist / 'stale.bin'
    dist.mkdir(exist_ok=True)
    stale.write_bytes(b'x')

    subprocess.run([sys.executable, 'build.py'], cwd=root, check=True)

    assert not stale.exists()
    assert sorted(path.name for path in dist.iterdir()) == ['boot.mpy', 'boot.py', 'mpy', 'web']
    assert (dist / 'web' / 'index.html').is_file()
    assert (dist / 'web' / 'assets' / 'index.css').is_file()
    assert (dist / 'web' / 'assets' / 'index.js').is_file()


def test_build_injects_runtime_config_overrides() -> None:
    root = Path(__file__).resolve().parents[1]
    dist = root / 'dist'
    payload_seed = (root / 'payload.dd').read_text(encoding='utf-8')

    subprocess.run(
        [
            sys.executable,
            'build.py',
            '--ap-ssid',
            'Studio Pico',
            '--ap-password',
            'keyboard42',
        ],
        cwd=root,
        check=True,
    )

    bundled = (dist / 'boot.py').read_text(encoding='utf-8')
    assert "AP_SSID='Studio Pico'" in bundled
    assert "AP_PASSWORD='keyboard42'" in bundled
    first_line = payload_seed.splitlines()[0].strip()
    assert first_line
    assert first_line in bundled


def test_build_emits_minified_bundle() -> None:
    root = Path(__file__).resolve().parents[1]

    subprocess.run([sys.executable, 'build.py'], cwd=root, check=True)
    bundled = (root / 'dist' / 'boot.py').read_text(encoding='utf-8')

    assert bundled.startswith('# Generated by build.py\n# ruff: noqa\n')
    assert len(bundled) < 260000
    ast.parse(bundled)
    assert (root / 'dist' / 'boot.mpy').is_file()


def test_build_skip_frontend_reuses_compiled_artifacts() -> None:
    root = Path(__file__).resolve().parents[1]
    dist_web = root / 'dist' / 'web'
    if not (dist_web / 'index.html').is_file():
        subprocess.run(
            ['npm', '--prefix', str(root / 'web'), 'run', 'build'],
            cwd=root,
            check=True,
        )

    result = subprocess.run(
        [sys.executable, 'build.py', '--skip-frontend'],
        cwd=root,
        check=True,
    )
    assert result.returncode == 0
    assert (root / 'dist' / 'boot.py').is_file()
    assert (root / 'dist' / 'boot.mpy').is_file()
    assert (dist_web / 'index.html').is_file()


def test_build_emits_compiled_mpy_tree() -> None:
    root = Path(__file__).resolve().parents[1]
    dist = root / 'dist' / 'mpy'

    subprocess.run([sys.executable, 'build.py'], cwd=root, check=True)

    compiled = sorted(path.relative_to(dist).as_posix() for path in dist.rglob('*.mpy'))
    assert 'boot.mpy' in compiled
    assert 'main.mpy' in compiled
    assert 'ducky/analysis.mpy' in compiled
    assert 'server/__init__.mpy' in compiled
    assert 'ducky/runtime.mpy' in compiled
