PAYLOAD_FILE = 'payload.dd'
DEFAULT_PAYLOAD = 'REM pico-bit starter payload\nREM STRING Hello from pico-bit\n'

RANDOM_CHAR_SETS = {
    'RANDOM_LOWERCASE_LETTER': 'abcdefghijklmnopqrstuvwxyz',
    'RANDOM_UPPERCASE_LETTER': 'ABCDEFGHIJKLMNOPQRSTUVWXYZ',
    'RANDOM_LETTER': 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ',
    'RANDOM_NUMBER': '0123456789',
    'RANDOM_SPECIAL': '!@#$%^&*()[]{}<>?!@#$%^&*-_=+;:,.\\/|',
    'RANDOM_CHAR': (
        'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'
        '!@#$%^&*()[]{}<>?!@#$%^&*-_=+;:,.\\/|'
    ),
}

LED_ON_COMMANDS = {
    'LED_R',
    'LED_G',
    'LED_B',
    'LED_ON',
}

SIMPLE_COMMANDS = {
    'ATTACKMODE',
    'DEFAULTDELAY',
    'DEFAULT_DELAY',
    'DEFAULTCHARDELAY',
    'DEFAULT_CHAR_DELAY',
    'DEFAULTCHARJITTER',
    'DELAY',
    'DISABLE_BUTTON',
    'ENABLE_BUTTON',
    'EXFIL',
    'HIDE_PAYLOAD',
    'INCLUDE',
    'INJECT_MOD',
    'INJECT_VAR',
    'RD_KBD',
    'RELEASE',
    'RESET',
    'RESTORE_ATTACKMODE',
    'RESTORE_HOST_KEYBOARD_LOCK_STATE',
    'RESTORE_PAYLOAD',
    'RESTART_PAYLOAD',
    'SAVE_ATTACKMODE',
    'SAVE_HOST_KEYBOARD_LOCK_STATE',
    'SLEEP_UNTIL_IDLE',
    'STOP_PAYLOAD',
    'TYPE_RATE',
    'VERSION',
    'WAIT_FOR_BUTTON_PRESS',
    'WAIT_FOR_CAPS_CHANGE',
    'WAIT_FOR_CAPS_OFF',
    'WAIT_FOR_CAPS_ON',
    'WAIT_FOR_NUM_CHANGE',
    'WAIT_FOR_NUM_OFF',
    'WAIT_FOR_NUM_ON',
    'WAIT_FOR_SCROLL_CHANGE',
    'WAIT_FOR_SCROLL_OFF',
    'WAIT_FOR_SCROLL_ON',
}

BLOCK_TERMINATORS = {
    'CATCH',
    'END_BUTTON',
    'END_EXTENSION',
    'END_FUNCTION',
    'END_IF',
    'END_STRING',
    'END_STRINGLN',
    'END_TRY',
    'END_WHILE',
    'ELSE',
    'ELSE IF',
    'ELSEIF',
}

NO_DELAY_COMMANDS = {
    'ATTACKMODE',
    'DELAY',
    'DEFAULTDELAY',
    'DEFAULT_DELAY',
    'DEFAULTCHARDELAY',
    'DEFAULT_CHAR_DELAY',
    'DEFAULTCHARJITTER',
    'DISABLE_BUTTON',
    'ENABLE_BUTTON',
    'EXFIL',
    'HIDE_PAYLOAD',
    'INCLUDE',
    'RD_KBD',
    'RESTORE_ATTACKMODE',
    'RESTORE_PAYLOAD',
    'SAVE_ATTACKMODE',
    'SAVE_HOST_KEYBOARD_LOCK_STATE',
    'RESTORE_HOST_KEYBOARD_LOCK_STATE',
    'SLEEP_UNTIL_IDLE',
    'TYPE_RATE',
    'VERSION',
}

SAFE_INTERNAL_DEFAULTS = {
    '_BUTTON_ENABLED': True,
    '_BUTTON_PUSH_RECEIVED': False,
    '_BUTTON_TIMEOUT': 0,
    '_BUTTON_USER_DEFINED': False,
    '_JITTER_ENABLED': False,
    '_JITTER_MAX': 20,
    '_RANDOM_MAX': 65535,
    '_RANDOM_MIN': 0,
    '_SYSTEM_LEDS_ENABLED': True,
}
