AP_IF: int

class WLAN:
    def __init__(self, interface: int) -> None: ...
    def active(self, value: bool | None = ...) -> bool: ...
    def config(self, *, ssid: str, password: str) -> None: ...
    def ifconfig(self) -> tuple[str, str, str, str]: ...
