AP_IF: int

class WLAN:
    IF_AP: int
    PM_NONE: int
    SEC_OPEN: int
    SEC_WPA2: int
    SEC_WPA_WPA2: int

    def __init__(self, interface: int) -> None: ...
    def active(self, value: bool | None = ...) -> bool: ...
    def config(self, *args, **kwargs) -> object: ...
    def ifconfig(self) -> tuple[str, str, str, str]: ...
