from __future__ import annotations

import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WEB_DIR = ROOT / 'web'
WEB_DIST_DIR = ROOT / 'dist' / 'web'
OUTPUT = ROOT / 'src' / 'web_assets.py'

MIME_TYPES = {
    '.css': 'text/css; charset=utf-8',
    '.html': 'text/html; charset=utf-8',
    '.js': 'application/javascript; charset=utf-8',
    '.json': 'application/json; charset=utf-8',
    '.svg': 'image/svg+xml',
    '.txt': 'text/plain; charset=utf-8',
}

HEADER = (
    '# Generated by scripts/asset_pipeline.py\n'
    '# ruff: noqa: E501\n'
    '# Source files live under web/ and compile into dist/web/.\n\n'
)


class FrontendBuildError(RuntimeError):
    pass


def build_frontend() -> None:
    try:
        subprocess.run(
            ['npm', '--prefix', str(WEB_DIR), 'run', 'build'],
            check=True,
            cwd=ROOT,
        )
    except FileNotFoundError as exc:
        raise FrontendBuildError(
            'npm is required to compile web assets. Run npm ci --prefix web first.'
        ) from exc
    except subprocess.CalledProcessError as exc:
        raise FrontendBuildError('frontend asset build failed') from exc


def _compiled_files() -> list[Path]:
    return sorted(path for path in WEB_DIST_DIR.rglob('*') if path.is_file())


def _constant_name(path: Path) -> str:
    relative = path.relative_to(WEB_DIST_DIR)
    name = relative.as_posix().upper()
    for char in './-':
        name = name.replace(char, '_')
    return 'ASSET_' + ''.join(char if char.isalnum() or char == '_' else '_' for char in name)


def _mime_type(path: Path) -> str:
    return MIME_TYPES.get(path.suffix.lower(), 'application/octet-stream')


def _routes_for(path: Path) -> list[str]:
    relative = path.relative_to(WEB_DIST_DIR).as_posix()
    routes = ['/' + relative]
    if relative == 'index.html':
        routes.insert(0, '/')
    stem = path.stem.split('.')[0]
    if stem == 'index' and path.suffix == '.css' and relative.startswith('assets/'):
        routes.append('/index.css')
    if stem == 'index' and path.suffix == '.js' and relative.startswith('assets/'):
        routes.append('/index.js')
    return routes


def _find_asset(stem: str, suffix: str) -> Path:
    """Return the first compiled asset matching assets/<stem>*<suffix>, or the plain name."""
    for candidate in sorted(WEB_DIST_DIR.glob(f'assets/{stem}*{suffix}')):
        return candidate
    return WEB_DIST_DIR / 'assets' / (stem + suffix)


def render_web_assets() -> str:
    compiled = _compiled_files()
    if not compiled:
        raise FrontendBuildError(
            f'compiled web assets are missing under {WEB_DIST_DIR.relative_to(ROOT)}. '
            'Run npm --prefix web run build.'
        )

    lines = [HEADER]
    asset_names: list[str] = []
    routes: list[tuple[str, str, str]] = []
    for path in compiled:
        name = _constant_name(path)
        asset_names.append(name)
        data = path.read_bytes()
        # Store as bytes so the server can write directly to the socket without
        # a str.encode() allocation on every request. Frozen bytes literals are
        # flash-resident in MicroPython, meaning no heap copy is made when the
        # server reads and sends them.
        lines.append(f'{name}: bytes = {repr(data)}\n\n')
        routes.extend((route, name, _mime_type(path)) for route in _routes_for(path))

    lines.append('STATIC_ASSET_NAMES: tuple[str, ...] = ' + repr(tuple(asset_names)) + '\n\n')
    lines.append('STATIC_ASSETS = (\n')
    for route, name, mime_type in routes:
        lines.append(f'    ({route!r}, {name}, {mime_type!r}),\n')
    lines.append(')\n\n')

    index_html = _constant_name(WEB_DIST_DIR / 'index.html')
    index_css = _constant_name(_find_asset('index', '.css'))
    index_js = _constant_name(_find_asset('index', '.js'))
    if index_html in asset_names:
        lines.append(f'INDEX_HTML: bytes = {index_html}\n')
        lines.append('LOGIN_HTML: bytes = INDEX_HTML\n')
    if index_css in asset_names:
        lines.append(f'INDEX_CSS: bytes = {index_css}\n')
        lines.append('PORTAL_CSS: bytes = INDEX_CSS\n')
    if index_js in asset_names:
        lines.append(f'INDEX_JS: bytes = {index_js}\n')
        lines.append('PORTAL_JS: bytes = INDEX_JS\n')
    lines.append('\n')

    exports = [
        *asset_names,
        'STATIC_ASSET_NAMES',
        'STATIC_ASSETS',
        'INDEX_HTML',
        'INDEX_CSS',
        'INDEX_JS',
        'LOGIN_HTML',
        'PORTAL_CSS',
        'PORTAL_JS',
    ]
    lines.append('__all__ = ' + repr(exports) + '\n')
    return ''.join(lines)


def sync_web_assets(check: bool = False) -> bool:
    build_frontend()
    rendered = render_web_assets()
    current = OUTPUT.read_text(encoding='utf-8') if OUTPUT.exists() else None
    if current == rendered:
        return False
    if check:
        raise Warning('src/web_assets.py is out of date. Run asset sync first.')
    OUTPUT.write_text(rendered, encoding='utf-8')
    return True


if __name__ == '__main__':
    sync_web_assets()
