from ducky.constants import ALLOW_UNSAFE_DEFAULT

AP_SSID: str = 'PicoBit'
AP_PASSWORD: str = '88888888'
ALLOW_UNSAFE: bool = ALLOW_UNSAFE_DEFAULT
PORTAL_AUTH_ENABLED: bool = True
PORTAL_USERNAME: str = 'admin'
PORTAL_PASSWORD: str = AP_PASSWORD
CORS_ALLOWED_ORIGIN: str = ''
CORS_ALLOW_CREDENTIALS: bool = False
